name: retroreviveapp
description: "A second hand thrift store"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.10.3

  # utiliey packages

  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12

  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8
  google_fonts: ^6.2.1

  #state Management
  get: ^4.6.6
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.4.0
  get_storage: ^2.1.1
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  #.....local assets
  assets:
    - assets/icons/
    - assets/images/onBoardingImages/
    - assets/logo/
    - assets/images/verification/
    - assets/images/topSellers/
    - assets/images/banners/
    - assets/images/products/

  #..... fonts
